# See https://upptime.js.org/docs/configuration
owner: RubenFixit
repo: upptime

sites:
  - name: Website (rubenfixit.com)
    url: https://rubenfixit.com
    icon: https://rubenfixit.com/wp-content/uploads/2021/05/cropped-rubenfixit-favicon-32x32.png
  - name: URL Shortner (rfix.me)
    url: https://rfix.me/test
    icon: https://rubenfixit.com/wp-content/uploads/2021/05/cropped-rubenfixit-favicon-32x32.png
  - name: Plex Website (plex.rubenfixit.com)
    url: $PLEX_WEBSITE_URL
    icon: https://www.plex.tv/wp-content/themes/plex/assets/img/favicons/favicon.ico
  - name: Plex Server
    url: $PLEX_SERVER_URL
    icon: https://www.plex.tv/wp-content/themes/plex/assets/img/favicons/favicon.ico
    __dangerous__disable_verify_host: true

status-website:
  cname: status.rubenfixit.com
  logoUrl: https://rubenfixit.com/wp-content/uploads/2021/05/cropped-rubenfixit-favicon-32x32.png
  name: RubenFixit Status
  introTitle: "RubenFixit's Servers Status"
  introMessage: The uptime status of servers managed by RubenFixit
  theme: dark
